### ISSUE TITLE
Naming convention for modules

### ISSUE THREAD

**Issue by badbole** [OCA/l10n-croatia#6]
We have specific problem, regarding naming of basic accounting localisation module.
According to well known naming convention, accounting localisation module shold be named :
l10n_hr_account. 
We have a problem because module with same name exists in odoo aps store, 
Author is Uvid d.o.o. 
Personaly, i do not find that module adequate for accountig localisation, and would like to develope and contribute with a much wider localisation module. 

I would like to check if name : **l10n_hr_account_oca** is acceptable name for such a localisation module. 
Iit will be futrher extended with **l10n_hr_account_fiscal_oca**  ( again: l10n_hr_account_fiscal is present as payed module in odoo app store, presented by same author: Uvid d.o.o.) 

As original author of l10n_hr_account_fiscal module 
(writen originaly for v7.0 -  https://github.com/badbole/fiskal_v70 ) 
I belive i have the right to clam it comunity and free of charge, but odoo accepted Uvid as author of that module, and sells it torugh app store as commercial module valued 100 eur.

Any opinions on solving this problem is more than appreciated.
If more info is needed, just ask.

**Comment by pedrobaeza** [comment]
@badbole I'm not anymore OCA's community manager. I think @dreispt and @simahawk can tell you.

**Comment by dreispt** [comment]
Hello @badbole, it sounds like a reasonable solution, and I don't think it goes against OCA guidelines.
Make sure it is clear that the authors and contributors are properly credited in the modules, and taht they agree with the OCA CLA.
Thanks!
